# This is a basic workflow that is manually triggered

name: Deploy

on: 
  release:
    types: [released, prereleased]
    
concurrency: prod-deploy

jobs:
  checkTag:
    runs-on: ubuntu-latest
    outputs:
      is-release-tag: ${{ steps.check-tag.outputs.is-release-tag }}
    steps:
      - name: Check tag
        id: check-tag
        run: |
          if [[ ${{ github.ref }} =~ refs\/tags\/v[0-9]{4}\.[0-9]{2}\.[0-9]{2}\..{7}$ ]]; then
            echo "::set-output name=is-release-tag::true"
            echo "This is a release tag"
          else
            echo "::set-output name=is-release-tag::false"
            echo "ERROR: Invalid tag name for a release. Correct example: v2021.05.27.d33cf8z"
            exit 1
          fi


  greet:
    needs: [checkTag]
    if: needs.checkTag.outputs.is-release-tag == 'true'
    
    runs-on: ubuntu-latest
    steps:
    - name: Send greeting
      continue-on-error: true
      run: |
        echo "Hello ${{ github.event.inputs.name }} ${GITHUB_REF##*/}"
        exit 1
