# This is a basic workflow that is manually triggered

name: Deploy


on: 
  release:
    types: [prereleased]
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"
