# This is a basic workflow that is manually triggered

name: Deploy

on: 
  release:
    types: [released]
jobs:
  checkTag:
    runs-on: ubuntu-latest
    outputs:
      release-tag: ${{ steps.check-tag.outputs.release-tag }}
    steps:
      - name: Check tag
        id: check-tag
        run: |
          if [[${{ github.ref }} =~ refs\/tags\/v[0-9]{4}\.[0-9]{2}\.[0-9]{2}\.\w{7}]]; then
            echo "::set-output name=run_jobs::true"
          else
            echo "::set-output name=run_jobs::false"
          fi

  greet:
    needs: [checkTag]
    if: needs.checkTag.outputs.release-tag == 'true'
    
    runs-on: ubuntu-latest
    steps:
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"
