# This is a workflow that is manually triggered

name: Create pre-release

on: workflow_dispatch
jobs:
  prerelease:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set version env
      run: echo "PRERELEASE_VERSION=$(echo v`date +%Y.%m.%d`.`git rev-parse --short HEAD`.rc)" >> $GITHUB_ENV
    - uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.WORKFLOW_PAT }}"
        automatic_release_tag: ${{ env.PRERELEASE_VERSION }}
        prerelease: true
        title: ${{ env.PRERELEASE_VERSION }}
