# This is a workflow that is manually triggered

name: Create pre-release

on: workflow_dispatch
jobs:
  prerelease:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
        fetch-depth: 0
    - name: Merge dev into main
      run: |
        git merge origin/dev
        git push origin master