name: Terragrunt Plan / Apply
on:
  pull_request:

jobs:
  terragrunt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Terraform + Terragrunt
      run: |
        brew install tfenv --build-from-source
